rm(list=ls())
source("dmc/dmc.R")
load_data ("dmc_1_1.RData")
load_data ("dmc_1_2.RData")
load_data("dmc_3_1.RData")
load_data ("dmc_3_2.RData")
load_data ("dmc_3_3.RData")
load_data ("dmc_3_4.RData")
load_data ("dmc_3_5.RData")
load_data ("dmc_4_2.RData")
load_data ("dmc_4_4.RData")
load_data ("dmc_4_5.RData")
load_data ("dmc_4_6_fixed.RData")
load_data ("dmc_4_6_random.RData")
load_data ("dmc_4_7_fixed.RData")
load_data ("dmc_4_7_random.RData")
load_data ("dmc_5_3.RData")
load_data ("dmc_5_4.RData")
load_data("dmc_5_5.RData")
load_data ("dmc_6_1.RData")
load_data ("dmc_6_2.RData")
load_data ("dmc_6_3.RData")
load_data ("dmc_6_4.RData")
load_data ("dmc_6_5.RData")
